version: "3.3"

services:
  db:
    environment:
      - POSTGRES_USER=mello_user
      - POSTGRES_PASSWORD=zenbudda4
      - POSTGRES_DB=mello_db
    image: postgres:latest
    networks:
      - mello
    ports:
      - 5405:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    image: bradsimpson213/mello
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://mello_user:zenbudda4@db/mello_db
      - PORT=5000
    networks:
      - mello
    ports:
      - 8080:5000

networks:
  mello:

volumes:
  postgres-data:
