"""create cards table

Revision ID: 34ff55c02e16
Revises: 78ac3e71770b
Create Date: 2020-07-14 20:19:02.763084

"""
from alembic import op
import sqlalchemy as sa
import datetime

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '34ff55c02e16'
down_revision = '78ac3e71770b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('listId', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=15), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listId'], ['lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE cards SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###
    # op.bulk_insert(cards_table,
    #     [
    #         { 'title': 'Create new project', "listId": 1, 'details': 'Create new React project','color': None,
    #           'completed': False, 'due_date': None, 'updated': datetime.datetime.now(), 'created': datetime.datetime.now() },
    #         {'title': 'Plan database structure', "listId": 1, 'details': 'Create models and schema', 'color': None,
    #             'completed': False, 'due_date': None, 'updated': datetime.datetime.now(), 'created': datetime.datetime.now()},
    #         {'title': 'Document project in readme file', "listId": 1, 'details': 'Create Readme file with MVP and Technology', 'color': None,
    #             'completed': False, 'due_date': None, 'updated': datetime.datetime.now(), 'created': datetime.datetime.now()},
    #         {'title': 'Code.  Like a whoe lot', "listId": 1, 'details': 'Get that code out on VSCode!', 'color': None,
    #             'completed': False, 'due_date': None, 'updated': datetime.datetime.now(), 'created': datetime.datetime.now()},
    #         {'title': 'Code some more.', "listId": 2, 'details': 'Are you done coding?  No?  Then code more!', 'color': None,
    #             'completed': False, 'due_date': None, 'updated': datetime.datetime.now(), 'created': datetime.datetime.now()}
    #     ]
    # )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
