"""create lists table

Revision ID: 78ac3e71770b
Revises: a860f4d402a8
Create Date: 2020-07-14 20:18:16.888976

"""
from alembic import op
import sqlalchemy as sa
import datetime

# revision identifiers, used by Alembic.
revision = '78ac3e71770b'
down_revision = 'a860f4d402a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    lists_table = op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_name', sa.String(length=50), nullable=False),
    sa.Column('boardId', sa.Integer(), nullable=False),
    sa.Column('card_order', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['boardId'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.bulk_insert(lists_table,
        [
            {'list_name': 'Project starting to do items', 'boardId': 2, 'card_order': [ "card-1", "card-2", "card-3", 'card-4'],
             'due_date': None, 'updated': datetime.datetime.now(), "created": datetime.datetime.now(), },
            {'list_name': 'In progress', 'boardId': 2, 'card_order': ["card-1"],
             'due_date': None, 'updated': datetime.datetime.now(), "created": datetime.datetime.now(), },
            {'list_name': 'Completed', 'boardId': 2, 'card_order': [ ],
             'due_date': None, 'updated': datetime.datetime.now(), "created": datetime.datetime.now(), }
        ]
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lists')
    # ### end Alembic commands ###
