"""create users table

Revision ID: 3181e039ecbd
Revises: 
Create Date: 2020-07-14 19:58:10.087768

"""
from alembic import op
import sqlalchemy as sa
from werkzeug.security import generate_password_hash
import datetime

# revision identifiers, used by Alembic.
revision = '3181e039ecbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    users_table = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('notification', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )

    op.bulk_insert(users_table,
        [
        {'username': 'demo1', 'email': 'demo@gmail.com',
            'hashed_password': generate_password_hash('demo1'), 'notification': 30000, 
            'theme': None, 'last_login': datetime.datetime.now(), 
            'created': datetime.datetime.now()},
        {'username': 'brads213', 'email': 'bradsimpson@icloud.com',
             'hashed_password': generate_password_hash('konadog4'), 'notification': 30000,
             'theme': None, 'last_login': datetime.datetime.now(),
             'created': datetime.datetime.now()},
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
