"""create boards table

Revision ID: a860f4d402a8
Revises: d73ec212fe9a
Create Date: 2020-07-14 20:17:08.813328

"""
from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision = 'a860f4d402a8'
down_revision = 'd73ec212fe9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    boards_table = op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('board_name', sa.String(length=50), nullable=False),
    sa.Column('board_image', sa.String(length=150), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('team', sa.Boolean(), nullable=True),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.Column('list_order', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(boards_table,
        [
            {'userId': 1, 'board_name': 'Coding Project', 'board_image': 'https://mello-zen-images.s3.amazonaws.com/zen-1.jpg',
             'public': False, 'team': False, 'teamId': None, 'list_order': [1,2], 'updated': datetime.datetime.now(),
             'created': datetime.datetime.now()},
            {'userId': 1, 'board_name': 'Home Remodel', 'board_image': 'https://mello-zen-images.s3.amazonaws.com/zen-2.jpg',
             'public': False, 'team': False, 'teamId': None, 'list_order': [2,3], 'updated': datetime.datetime.now(),
             'created': datetime.datetime.now()},
            {'userId': 1, 'board_name': 'Work Project', 'board_image': 'https://mello-zen-images.s3.amazonaws.com/zen-3.jpg',
             'public': False, 'team': True, 'teamId': 1, 'list_order': [1,3], 'updated': datetime.datetime.now(),
             'created': datetime.datetime.now()},
            {'userId': 2, 'board_name': 'Coding Project', 'board_image': 'https://mello-zen-images.s3.amazonaws.com/zen-1.jpg',
             'public': False, 'team': False, 'teamId': None, 'list_order': [1, 2], 'updated': datetime.datetime.now(),
             'created': datetime.datetime.now()},
            {'userId': 2, 'board_name': 'Home Remodel', 'board_image': 'https://mello-zen-images.s3.amazonaws.com/zen-2.jpg',
             'public': False, 'team': False, 'teamId': None, 'list_order': [2, 3], 'updated': datetime.datetime.now(),
             'created': datetime.datetime.now()},
            {'userId': 2, 'board_name': 'Work Project', 'board_image': 'https://mello-zen-images.s3.amazonaws.com/zen-3.jpg',
             'public': False, 'team': True, 'teamId': 1, 'list_order': [1, 3], 'updated': datetime.datetime.now(),
             'created': datetime.datetime.now()}
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boards')
    # ### end Alembic commands ###
